### ISSUE TITLE
Running Mutiple Jobs with mutiple readers and writers asynchronously

### ISSUE THREAD

**Issue by ishansrivastava** [NorthConcepts/DataPipeline-Examples#9]
Hello,
I am facing some challenges while using this module. So, can you please help me in overcoming that.

Issue:
I am having a many to many case. So basically I want to run two jobs asynchronously with their own reader and writer for example:

Job1.run(reader1,writer1)
Job2.run(reader2,writer2)

  I just want to know is it possible. If, yes then how and if you want me to share the patch of code `which` I am facing problem with please do let me know.

**Comment by DeleTaylor** [comment]
Yes, it's definitely possible to run multiple jobs in parallel.

```
Job job1 = Job.runAsync(reader1,writer1);
Job job2 = Job.runAsync(reader2,writer2);

job1.waitUntilFinished();
job2.waitUntilFinished();

```
Read more here: 
1. https://northconcepts.com/javadocs/com/northconcepts/datapipeline/job/Job.html#runAsync-com.northconcepts.datapipeline.core.DataReader-com.northconcepts.datapipeline.core.DataWriter-
2. https://northconcepts.com/docs/user-guide/#asynchronous-jobs

**Comment by ishansrivastava** [comment]
Hi,
Thanks for replying sir(DeleTaylor) really appreciate it.I tried what you suggested but its just executing the first job .In the second job reader is having record but the writer is not writing it.Any suggestions to counter it?

**Comment by ishansrivastava** [comment]
Hey,
My bad i found out the mistake why it was not inserting , it seems there was one not null column in which it was trying to insert a null value (; . Just one question sir i don't seem to understand why it was not working before.I did as given below:

Job job1=new Job(reader1,writer1);
Job job2=new Job(reader2,writer2);
job1.runAsync(reader1,writer1);
job2.runAsync(reader2,writer2);

is there any reason that the above code was not working.

**Comment by ishansrivastava** [comment]
Hello sir,
Is their a way to insert and update in one tabe using jdbcwriter?

**Comment by DeleTaylor** [comment]
You can update if a record exists or insert if it doesn't using the `JdbcUpsertWriter`.

This example works across all DBs --> https://northconcepts.com/docs/examples/upsert-records-to-a-database-using-insert-and-update/.  You can flip the flag to choose whether the insert or the update is attempted first.

You might be able to get better performance using an upsert/merge feature that's built into your database.  Have a look for "upsert" on this page in case there's one specific for your database:  https://northconcepts.com/docs/examples/tag/jdbc/.
